type: php
docroot: .Build
additional_hostnames:
  - 13.typo3-request-profiler
  - 14.typo3-request-profiler
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp -r /var/www/html/.ddev/.setup/templates/. /var/www/html/.Build/ && bash /var/www/html/.ddev/.setup/scripts/write-git-info.sh
